### PR TITLE
User/hshami/color code output

### PR DESCRIPTION
**Pull request by mhshami01**
addressing bug 10112403

### CODE REVIEW

**Comment by cindydeng1998** [comment]
Do you have a screenshot of what the new output looks like? :)

**Review by cindydeng1998 — APPROVED** [review]
🌞

**Comment by mhshami01** [comment]
> Do you have a screenshot of what the new output looks like? :)

image

**Review by vikas0212git — APPROVED** [review]

**Review by marianan — APPROVED** [review]
:shipit:

**Pull request merged**
